server:
    # port: 1200
    port: 1300
    servlet:
        context-path: /tasty-town

spring:
    application:
        name: backend
    # security:
    #     user:
    #         name: Ashutosh
    #         password: 00123400
    datasource:
        # url: jdbc:postgresql://localhost:5432/tasty-town
        # username: postgres
        # password: root
        url: jdbc:mysql://localhost/tasty-town
        username: root
        password: root
    # jpa:
    #     hibernate:
    #         ddl-auto: update
    #     show-sql: true

upload:
    file:
        dir: images

order:
    delivery:
        fee: 30
    tax:
        rate: 0.1